# .github/workflows/ci.yml
name: CI
on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node only — no pnpm cache here
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Activate pnpm via Corepack and prove it's on PATH
      - name: Activate pnpm (Corepack)
        run: |
          set -euxo pipefail
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v
          which pnpm

      # Cache pnpm store (now that pnpm exists)
      - name: Compute pnpm store path
        id: pnpm-cache
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: pnpm-store-

      - name: Install
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0 # skip local hooks in CI

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
        env:
          NEXT_TELEMETRY_DISABLED: 1
